### ISSUE TITLE
Fail: stringify object with to_json (mrbgems: mruby-json)

### ISSUE THREAD

**Issue by katzer** [mattn/mruby-json#21]
The following test from ruby-json fails:

```
Fail: stringify object with to_json (mrbgems: mruby-json)
 - Assertion[1] Failed: Expected to be equal
    Expected: "{\"foo\":\"foo\"}"
      Actual: "\"#<Foo:0x998980>\""
```

BTW there's no visible test summary on travis. Are you sure that they get executed?

**Comment by mattn** [comment]
Just updated .travis.yml

https://travis-ci.org/mattn/mruby-json/builds/246434987

**Comment by mattn** [comment]
Seems not failed on travis. What test did you do?

**Comment by katzer** [comment]
Seems like it fails with mruby-1.2.0 by just executing your tests without other interferences.

**Comment by katzer** [comment]
I can confirm it fails with mruby-1.2.0 only. With mruby-head its green.

**Comment by mattn** [comment]
Do you use still mruby-1.2.0?

**Comment by mattn** [comment]
Thanks. so closing.
