### ISSUE TITLE
[mruby-1.3.0] mruby-json/test/json.rb:151: syntax error, unexpected '{'

### ISSUE THREAD

**Issue by katzer** [mattn/mruby-json#33]
The following errors occur with latest mruby-json and mruby-1.3.0:
```
/home/mruby/code/mruby/build/mrbgems/mruby-json/test/json.rb:151:49: syntax error, unexpected '{', expecting '}'
/home/mruby/code/mruby/build/mrbgems/mruby-json/test/json.rb:151:61: syntax error, unexpected '}', expecting keyword_end
```

Note: The errors only occur with mruby-1.3.0, not with mruby-1.4.0 or newer.

**Comment by mattn** [comment]
What json use?

**Comment by katzer** [comment]
The message comes up when you try to compile mrbtest and mruby-json is in your dependency list.

**Comment by mattn** [comment]
OMG, Thanks for your report. I'll look into it in later.
