### ISSUE TITLE
Test "stringify object with boolean key and float value" fails on mruby 3.0.0

### ISSUE THREAD

**Issue by okuramasafumi** [mattn/mruby-json#44]
Hi, I'm new to mruby, but I found a test failure on mruby 3.0.0.

I added `mruby-json` as a dependency to my mgem and I found the following output.

```
Fail: stringify object with boolean key and float value (mrbgems: mruby-json)
 - Assertion[1]
    Expected: "{\"true\":5}"
      Actual: "{\"true\":5.0}"
```

**Comment by okuramasafumi** [comment]
Related: https://github.com/mattn/mruby-json/pull/40

**Comment by okuramasafumi** [comment]
https://github.com/mruby/mruby/commit/1974aa0f723bb1971d46ea2185d6b2f4c6581d55
This change comes from the commit above, which made mruby to be compatible with CRuby.
PR #40 is exactly what we need since this is not a bug but an intentional change.

**Comment by genya0407** [comment]
I encountered the same situation.

Personally, I think it's O.K. to change `5.0` to, say, `5.1` because the concern of the test seems to be checking `boolean key and float value`, not checking the specification of `trailing zero` of `Float#to_s`.

**Comment by mattn** [comment]
@take-cheeze What do you think?

**Comment by take-cheeze** [comment]
I'm not currently using or developing mruby heavily so not much to say.
If the community can pay cost to maintain 2 tests for mruby 2 and 3 let's maintain it.
If 2 will be still going to be used for a while, keeping the tests seems reasonable.
Or just removing test case for corner case would be more easier solution.

**Comment by mattn** [comment]
@take-cheeze Thank your comment. I prefer that mruby-json remove the tests since we can use to_i or to_f for manipulating the values.

**Comment by palkan** [comment]
Hey! Any updates? 

> removing test case for corner case would be more easier solution.

Sound like a reasonable quick fix 🙂

**Comment by mattn** [comment]
Removed the test.
